# Generated by Django 5.2.5 on 2025-12-11 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_post_image'),
    ]

    operations = [
    ]
