# Generated by Django 5.2.5 on 2025-12-16 11:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direct_message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dm',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
