# Generated by Django 5.2.5 on 2025-12-17 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direct_message', '0004_conversation_message_delete_dm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='last_message',
        ),
        migrations.AlterField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_message', to='direct_message.conversation'),
        ),
    ]
