# Generated by Django 5.2.5 on 2025-12-17 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direct_message', '0005_remove_conversation_last_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='last_sent',
            field=models.DateField(auto_now=True),
        ),
    ]
