# Generated by Django 5.2.5 on 2025-12-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direct_message', '0006_conversation_last_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_image_upload_path'),
        ),
    ]
