# Generated by Django 5.2.5 on 2025-12-18 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('direct_message', '0007_message_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='timestrap',
            new_name='timestamp',
        ),
    ]
