# Generated by Django 5.2.5 on 2025-12-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direct_message', '0008_rename_timestrap_message_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='last_sent',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
