# Generated by Django 5.2.5 on 2025-12-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direct_message', '0009_alter_conversation_last_sent_alter_message_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
