# Generated by Django 5.2.5 on 2025-12-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direct_message', '0010_message_edited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
