# Generated by Django 5.2.5 on 2025-12-20 09:55

import direct_message.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direct_message', '0011_alter_message_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='edited',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_seen',
        ),
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=direct_message.models.chat_image_upload_path),
        ),
    ]
