# Generated by Django 5.2.5 on 2025-12-11 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='saved_post_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
