# Generated by Django 5.2.5 on 2025-12-11 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profilee', '0002_profile_saved_post_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='address',
            new_name='location',
        ),
    ]
