# Generated by Django 5.2.5 on 2025-12-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilee', '0005_alter_profile_location_alter_profile_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
