# Generated by Django 5.2.5 on 2025-12-17 17:14

import profilee.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilee', '0007_alter_profile_bio_alter_profile_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='default-user.png', upload_to=profilee.models.user_profile_image_upload_path),
        ),
    ]
